[phases.setup]
apt = ["python3", "python3-pip", "python3-dev", "gcc"]

[phases.build]
commands = ["pip install -r flask-server/app/requirements.txt"]

[phases.start]
commands = ["python flask-server/app/run.py"]
